branches:
  only:
    - master
language: generic
# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

script:
- mkdir binaries
# Build the package, its tests, and its docs and run the tests
- stack --no-terminal build --ghc-options -O2 --test --haddock --no-haddock-deps --local-bin-path binaries --copy-bins

before_deploy:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - export TAG_VERSION="v0.1.$TRAVIS_BUILD_NUMBER"
  - git tag $TAG_VERSION

deploy:
  on:
    branch: master
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "binaries/*"
  skip_cleanup: true
  prerelease: true
